Repository mtt-lang/mtt-lang, pull requests merged in 2021-04, with the labels that each got.

#63 doc: split README and update description and grammar
  HACKING.md
  README.md
Labels: documentation

#54 Improve error reporting
  bin/mtt.ml
  src/Env.ml
  src/Typechecker.ml
  test/typechecker/modal-counterexamples.t
  test/typechecker/modal.t
Labels: error-reporting

#67 mttweb: some more code deduplication
  web/mttweb.ml
Labels: refactoring

#72 refactor: rename src/ to core/
  core/Ast.ml
  core/Env.ml
  core/Evaluator.ml
  core/Evaluator.mli
  core/Id.ml
  core/Lexer.ml
  core/Location.ml
  core/Location.mli
  core/MttError.ml
  core/Nat.ml
  core/Nat.mli
  core/Parser.mly
  core/ParserErrors.messages
  core/ParserInterface.ml
  core/ParserInterface.mli
  core/PrettyPrinter.ml
  core/PrettyPrinter.mli
  core/Typechecker.ml
  core/Typechecker.mli
  core/Util.ml
  core/dune
Labels: refactoring
